### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by olsonperrensen** [olsonperrensen/Tomorrowland#1]
### Main purpose: Manage and facilitate the rental of accommodations

- [ ] Park is base class and can have derived classes: CenterParks, Sunparks, VacationParks
    - [ ] Park not only into Accommodations! Offers Services as well  (children's paradise, sportshall, subtropical swimming paradise, bicycle rental, bowling alleys, pedal boat rental)
- [ ] Accommodations can be of two types: HotelRoom or Bungalow
    - [ ] Common traits of both: id, luxury_level (comfort, premium, vip), max_ppl, surface area, bathroom (w w/o bath) + all must be adaptable within MGMT
    - [ ] Unique to HR: floor_nr, inner_positioning (road side, lake side), n_beds, baby_crib_presence
    - [ ] Unique to Bungalow: n_bedrooms, high luxury ? bluray_surround, bbq_machine, bed_making_srv, breakfast_srv : None
- [ ] Only owner can CRUD parks, and parks CRUD accommodations:
    - [ ] Therefore owner can CRUD accommodations as well
    - [ ] Employees on the other hand can only modify accommodations alone
- [ ] Customer + Booking logs should be stored
    - [ ] CRUDed by staff only
    - [ ] Bookings should contains acc + services used
    - [ ] 1 Booking = tot 3 Accommodations per park 
- [ ] Customers can register themselves and book accommodations, change them as well but NOT delete them. 
- [ ] Customers can edit their gegevens
- [ ] Deleting booking only gebeurt via staff
